apiVersion: apps/v1

kind: Deployment

metadata:
  name: app-kotlin-deployment
  labels:
    app: app-kotlin

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-kotlin
  template:
    metadata:
      labels:
        app: app-kotlin
    spec:
      containers:
        - name: app-kotlin
          image: iskanred/app_kotlin:1.0.0
          ports:
            - containerPort: 8080

