apiVersion: v1

kind: Service

metadata:
  name: app-kotlin-service
  labels:
    app: app-kotlin

spec:
  type: LoadBalancer
  selector:
    app: app-kotlin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
