- name: Wipe Application using Docker
  when:
    - web_app_full_wipe
    - web_app_deployment_way == "docker"
  block:
    - name: Remove container
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent

    - name: Remove image
      docker_image:
        name: "{{ docker_image }}"
        state: absent

- name: Wipe Application using Docker-Compose
  when:
    - web_app_full_wipe
    - web_app_deployment_way == "compose"
  block:
    - name: Check Docker-Compose file exists
      stat:
        path: "{{ docker_compose_filepath }}"
      register: compose_file_stat

    - name: Remove Docker-Compose services
      when: compose_file_stat.stat.exists
      command: "docker-compose -p {{ app_name }} down --remove-orphans"
      args:
        chdir: "{{ app_dir }}"

    - name: Remove application's directory with it's content
      file:
        path: "{{ app_dir }}"
        state: absent