- name: Ping all hosts
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

- name: Deploy go web_app
  hosts: all
  become: yes
  roles:
    - web_app
  vars:
    app_name: go_app
    container_name: moscow_time_go
    image: "iviosab/moscow_time_go"
