apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - host: app.python
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python-service
                port:
                  number: 80
    - host: app.kotlin
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-kotlin-service
                port:
                  number: 8080
