apiVersion: v1

kind: Config
current-context: minikube

clusters:
  - name: minikube
    cluster:
      server: https://localhost:49154
      certificate-authority: {path to cert}
      extensions:
        - name: cluster_info
          extension:
            provider: minikube.sigs.k8s.io
            version: v1.31.2
            last-update: Tue, 31 Oct 2023 00:48:12 MSK

users:
  - name: minikube
    user:
      client-certificate: {path to client cert}
      client-key: {path to client key}

contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
      namespace: default
      extensions:
        - name: context_info
          extension:
            provider: minikube.sigs.k8s.io
            version: v1.31.2
            last-update: Tue, 31 Oct 2023 00:48:12 MSK
