- name: Install pip
  block:
    - name: Install python3 via apt
      apt:
        name: python3
        state: present

    - name: Install python3-pip via apt
      apt:
        name: python3-pip
        state: present
