# Uses apt because it is pre-installed on Debian / Ubuntu
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module
- name: Update apt
  apt:
    update_cache: true
