apiVersion: v1

kind: Service

metadata:
  name: app-python-service
  labels:
    app: app-python

spec:
  type: LoadBalancer
  selector:
    app: app-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
